### ISSUE TITLE
data dir not installing via conda-forge

### ISSUE THREAD

**Issue by jlaura** [rbeyer/hiproc#1]
* pyrise version:
* Python version: 3.9.5
* Operating System: Centos7

### Description

Installation via conda-forge is not installing the data directory. Perhaps because it does not have an `__init__.py` file and/or it is not specified in the setup.py.

### What I Did

```
conda create -n hiproc
conda activate hiproc
mamba install -c conda-forge hiproc
condo activate --stack isis5.0.0
hiproc

> `FileNotFoundError: [Errno 2] No such file or directory: '/home/jlaura/anaconda3/envs/hiproc/lib/python3.9/site-packages/hiproc/data/HiJitReg.conf'`
```

**Comment by jlaura** [comment]
As a work around, I cloned the repo and copied the data files over, so not a big issue.

**Comment by rbeyer** [comment]
Hmmmm, maybe I didn't understand the `package_data` element in setup.py as well as I thought, or maybe I understand it just fine, but I need to do extra work via conda-forge.  I'll work on it.

**Comment by rbeyer** [comment]
Ah, needed to have things in `MANIFEST.in` also, duh.  The new 0.7.0 release (which will propagate to conda-forge soon, I'm sure) will have that, and some other improvements.  However, after that, I realized that I left out a dependency: multidict.  So you'll need to manually `conda install multidict` to get 0.7.0 to work (grr).  I probably screwed up some other stuff, so I'll hold off on cutting 0.7.1 to make sure that the data directory and other things are working as expected.
